spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muser
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      
